// react-exercise/src/components/Assignment.tsx
//import React from 'react'
import ContentItem from "./ContentItem";
import ElevatorBank from "./assignment-components/ElevatorBank"; 

const Assignment = () => {

const elevatorData = {
  floors: 6,
  elevators:  [{floors: [{start: 1, end: 6}]}]
}

  return (
    <div>
     <ContentItem heading="Application" >
      <ElevatorBank  elevatorData={elevatorData}/>
     </ContentItem>
    </div>
  )
}

export default Assignment

// vue-exercise/src/components/Assignment.vue
<script>
import ContentItem from './ContentItem.vue'
import ElevatorBank from './assignment-components/elevator-bank.vue';

export default {
  components: {
    ContentItem,
    ElevatorBank,
  },
  data() {
    return {
      elevatorData: {
        floors: 6,
        elevators: [{floors: [{start: 1, end: 6}]}]
      }
    }
  }
}


</script>

<template>
  <ContentItem>
    <template #heading>Application</template>
    <ElevatorBank 
      :elevator-data="elevatorData"
    />
  </ContentItem>
</template>
