// vue-exercise/src/components/assignment-components/panel.vue
<script>
import ElevatorButton from './button.vue'

export default {
    name: "panel",
    components: {
        ElevatorButton,
    },
    props: {
        panelType: "default",
        floorNumber: 0,
        isFire: {
            type: Boolean,
            default: false
        },
        panelButtonConfiguration:Array
    },
    data() {
        return {
            buttonConfiguration: [],
            emitTarget: -1,
        }
    },
    created() {
        this.buttonConfiguration = this.panelButtonConfiguration.map((button) => {
            let label = button === "fire" ? "fire" : button === "emergency" ? "emergency" : button === "down" ? "&darr;" : button === "up" ? "&uarr;" : button === "alert" ? "alert" : button === "" ? "&nbsp;" : button + "";
            let event = button === "" ? "" : isNaN(button) ? button : "destination"; 
            let data = isNaN(button) ? this.floorNumber : button;
            return {
                buttonLabel: label,
                buttonEvent: event,
                buttonData: data
            };
            ;
        });

        this.emitTarget = this.floorNumber;
    },
    emits: ['up', 'down', 'emergency', 'fire', 'destination'],
    methods: {
        handleUp(data) {
            // if (this.isFire) return;
            this.$emit('up', data);
        },
        handleDown(data) {
            // if (this.isFire) return;
            this.$emit('down', data);
        },
        handleEmergency(data) {
            if (this.isFire) return;
            this.$emit('emergency', data);
        },
        handleFire(data) {
            this.$emit('fire', data);
        },
        handleDestination(data) {
            if (this.isFire) return;
            this.$emit('destination', data);
        },
    },
}
</script>

<template>
    <ElevatorButton 
        v-for="(elevatorButton, index) in buttonConfiguration"
        :button-label="elevatorButton.buttonLabel"
        :button-event="elevatorButton.buttonEvent"
        :button-data="elevatorButton.buttonData"
        @destination="handleDestination"
        @down="handleDown"
        @up="handleUp"
        @emergency="handleEmergency"
        @fire="handleFire"
    />
</template>

<style scoped>
</style>

// react-exercise/src/components/assignment-components/Panel.tsx
//import React from 'react'
import '../../styles/Assignments.css';
import ElevatorButton from './ElevatorButton';

interface panelProps {
        panelType: string;      // "default"
        floorNumber:number;     // 0
        panelButtonConfiguration: string []; 
        destination?: (data:number) => void;  
        upClick?: (data:number) => void;  
        downClick?: (data:number) => void;  
}

const Panel = (props: panelProps) => {
  
  const buttonConfiguration = props.panelButtonConfiguration.map ((button) => {
        const label = (button === "down") ? "↓" : (button === "up") ? "↑" : (button === "") ? "" : button + "";
        const event = (button === "") ? "" : isNaN(parseInt(button)) ? button : "destination";
        const data = isNaN(parseInt(button)) ? props.floorNumber.toString() : button;
        return {
              buttonLabel: label,
              buttonEvent: event,
              buttonData: data
            } 
  });
  
  const handleClick = (btnLabel:string, btnEvent: string, btnData:string) =>  {
    if (btnLabel === "↑") {
      if (props.upClick) {
        props.upClick(parseInt(btnData));
      }
    } else if (btnLabel === "↓") {
        if (props.downClick) {
          props.downClick(parseInt(btnData));
        }
    }
  };
  
  const handleDestination /*eslint-disable-line @typescript-eslint/no-unused-vars*/ = (data:number) => {
     if (props.destination) {
       props.destination(data);
     }
  };

  return (
    <div>
       {
        buttonConfiguration.map((elevatorButton /*, index*/) => {
            return (
                <ElevatorButton buttonLabel={elevatorButton.buttonLabel} buttonEvent={elevatorButton.buttonEvent} buttonData={elevatorButton.buttonData} 
                 onButtonClick={handleClick} > 
                {elevatorButton.buttonLabel}
                </ElevatorButton>
            )
          })
        }
    </div>
  )
}

//set default props, deprecated to be replaced
Panel.defaultProps = {
    panelType: "default",
    floorNumber: 0,
    panelButtonConfiguration: []
};


export default Panel
