// react-exercise/src/components/assignment-components/Elevator.tsx
//import React from 'react'
import Door from './Door';
import Panel from './Panel';

import '../../styles/Assignments.css';

import {FloorRequestType} from './FloorRequestType';
import { useState, useEffect, useRef} from 'react';

interface ElevatorProps {
   panelType: string;
   elevatorPanelButtonConfiguration: string[];
   index: number;
   floorRequest: FloorRequestType;
}

const Elevator = ({panelType="default", elevatorPanelButtonConfiguration, index=0, floorRequest= {floorNumber:-1, direction:""}}: ElevatorProps) => {

const [isMoving, setIsMoving] = useState(false);
const [destinationQueue, setDestinationQueue] = useState<number[]>(() => []);
const [elevatorID, setElevatorID] = useState("");
const [doorStatus, setDoorStatus] = useState("CLOSED");

const currentDirectionRef = useRef("");
const currentFloorRef = useRef(1);
const previousFloorRef = useRef(-1);
const targetFloorRef = useRef(-1);
const currentMoveTimeoutRef = useRef(-1);
const destinationQueueRef = useRef<number[]>([]);

useEffect(() => {
    setElevatorID(`Elevator # ${index + 1}`);
}, [index]);

useEffect(() => {
    if (floorRequest?.floorNumber !== undefined && floorRequest?.floorNumber > 0 &&  floorRequest?.direction !== "") {
        destinationQueueRef.current.push(floorRequest.floorNumber);
        setDestinationQueue(prevQueue => [...prevQueue, floorRequest.floorNumber]);  
    }
}, [floorRequest]);

const move = () => {
  const destinationFloor:number = destinationQueueRef.current[0]; 

  if (currentFloorRef.current === destinationFloor){
      destinationQueueRef.current = (destinationQueueRef.current.length > 1) ? destinationQueueRef.current.slice(1) : [];
      if (destinationQueue.length > 1 ) { setDestinationQueue(prevQueue => prevQueue.slice(1)) } else { setDestinationQueue([]);}
      handleArrival();
  } else {
    const currFloor = currentFloorRef.current;
    const direction =  currFloor < destinationFloor ? "up" : currFloor > destinationFloor ? "down" : "";
    if (direction !== "" ) {
        setIsMoving(() => true);
  
        let target = currFloor;
        if (direction === "up"){
          target++;
        }
        if (direction == "down"){
          target--;
        }
        currentFloorRef.current = target
        targetFloorRef.current = destinationFloor;
        previousFloorRef.current = currFloor;
        currentDirectionRef.current = direction;

        const timeoutId = setTimeout(() => {
          move();
        }, 3000);
        currentMoveTimeoutRef.current = timeoutId;
    }
  }
};

useEffect(() => {
  if (!isMoving && destinationQueue.length > 0){
      move();
  }
}, [destinationQueue.length , isMoving]);  

const handleArrival = () => {
    clearTimeout(currentMoveTimeoutRef.current);
    setTimeout(() => {
        setTimeout(() => {
            setDoorStatus(() => "OPENING");
            setTimeout(() => {
                setDoorStatus(() => "OPEN");
                setTimeout(() => {
                    setDoorStatus(() => "CLOSING");
                    setTimeout(() => {
                        setDoorStatus(() => "CLOSED");
                        if (destinationQueueRef.current.length > 0 || destinationQueue.length > 0 )  {
                            move();
                        }
                    }, 3000);
                }, 3000);
            }, 3000);
        }, 3000);
        setIsMoving(false); 
    }, 3000);
};

const handleDestination  = (data:number) => {
    if (data > 0) {
      if (!destinationQueue.includes(data)) {
         setDestinationQueue(prevQueue => [...prevQueue, data]);
      }
      if (!destinationQueueRef.current.includes(data)) {
         destinationQueueRef.current.push(data);
      }
    }
};

  return (
    <div className="elevator">
      <h1>{elevatorID}</h1>
      <div className="elevator-panel">
       Panel: 
       <Panel  floorNumber={-1} panelType={panelType} panelButtonConfiguration={elevatorPanelButtonConfiguration} destination={handleDestination} />
      </div> 
      <Door  doorStatus={doorStatus} />
      <div className="status">
          <span>{isMoving ? `CURRENT FLOOR IS ${previousFloorRef.current}.` : `CURRENT FLOOR IS ${currentFloorRef.current}.`}</span> &nbsp;&nbsp;
          <span>{isMoving && currentDirectionRef.current === 'up' ? `ASCENDING TO FLOOR ${targetFloorRef.current}.` : ''}</span>
          <span>{isMoving && currentDirectionRef.current === 'down' ? `DESCENDING TO FLOOR ${targetFloorRef.current}.` : ''}</span>
      </div>

        <div>QUEUED FLOORS:</div>
        <div className="queue">
             {destinationQueue.map (destination => {
                return (
                  <div> {destination}</div>
                )
             })
             }
        </div>
    </div>
  )
}

Elevator.defaultProps = {
  panelType: "default",
  index: 0,
  floorRequest: {}
};


export default Elevator

// vue-exercise/src/components/assignment-components/elevator.vue
<script>
import Panel from './panel.vue'
import Door from './door.vue'

export default {
    name: "elevator",
    components: {
        Panel,
        Door,
    },
    props: {
        panelType: "default",
        elevatorPanelButtonConfiguration: Array,
        index: {
            type: Number,
            default: 0
        },
        floorRequest: {}, 
    },
    data() {
        return {
            isMoving: false,
            currentDirection: "",
            doorStatus: "CLOSED",
            destinationQueue: [],
            isAvailable: false,
            panelButtonConfiguration: [],
            elevatorID : "",
            currentFloor: 1,
            previousFloor: -1,
            targetFloor: -1,
            currentMoveTimeout: -1,
        }
    },
    created() {
        this.elevatorID = `Elevator # ${this.index +1 }`;
        this.panelButtonConfiguration = this.elevatorPanelButtonConfiguration;
        this.incomingRequest = this.floorRequest;
    },
    watch: {
        floorRequest: {
            immediate: true,
            deep: true,
            handler (newFloorRequest){
                //newFloorRequest comes in with two properties: the floorNumber, and a direction: "up" or "down"
                if (newFloorRequest?.floorNumber !== undefined){
                    this.destinationQueue.push(newFloorRequest.floorNumber);
                }
            }
        },
        destinationQueue: {
            immediate: true,
            handler (oldQueue, newQueue){
                if (!this.isMoving){
                    this.move();
                }
            },
            deep: true
        },
    },
    methods: {
        move(){
            if (this.currentFloor === this.destinationQueue[0]){
                this.destinationQueue.shift();
                this.handleArrival();
            } else {
                this.isMoving = true;
                this.currentDirection = this.currentFloor < this.destinationQueue[0] ? "up" : this.currentFloor > this.destinationQueue[0] ? "down" : "";
                this.targetFloor = this.destinationQueue[0];
                let target = this.currentFloor;
                this.previousFloor = this.currentFloor;
                if (this.currentDirection === "up"){
                    target++;
                }
                if (this.currentDirection == "down"){
                    target--;
                }
                this.currentFloor = target;
                this.currentMoveTimeout = setTimeout(() => {
                    this.move();
                }, 3000);
            }
        },
        handleArrival(){
            clearTimeout(this.currentMoveTimeout);
            setTimeout(() => {                
                setTimeout(() => {
                    this.doorStatus = "OPENING";
                    setTimeout(() => {
                        this.doorStatus = "OPEN";
                        setTimeout(() => {
                            this.doorStatus = "CLOSING";
                            setTimeout(()=> {
                                this.doorStatus = "CLOSED";
                                setTimeout(()=>{
                                    if (this.destinationQueue.length > 0){
                                        this.move();
                                    }
                                }, 3000);
                            }, 3000);
                        }, 3000);
                    }, 3000);
                }, 3000);
                this.isMoving = false;
            }, 3000);
        },
        handleDestination(data) {
            if (!(this.destinationQueue.find((i) => i === data))){
                this.destinationQueue.push(data);
            }
        },
    }
}
</script>

<template>
    <div class="elevator">
        <h1>{{ this.elevatorID }}</h1>
        <div class="elevator-panel">
            Panel: 
            <Panel 
                :floor-number="-1" 
                :panel-type="panelType" 
                :panel-button-configuration="this.panelButtonConfiguration"
                @destination="handleDestination"
            />
        </div>
        <Door :door-status="doorStatus" />
        <div class="status">
            <span v-if="isMoving">CURRENT FLOOR IS {{ previousFloor }}.</span>
            <span v-else>CURRENT FLOOR IS {{ currentFloor }}.</span> &nbsp;
            <span v-if="isMoving && currentDirection === 'up'">ASCENDING TO FLOOR {{ this.targetFloor }}.</span>
            <span v-if="isMoving && currentDirection === 'down'">DESCENDING TO FLOOR {{ this.targetFloor }}.</span>
        </div>
        <div>QUEUED FLOORS:</div>
        <div class="queue">
            <div v-for="destination in destinationQueue">{{ destination }}</div>
        </div>
    </div>
</template>

<style scoped>
.elevator {
    display: flex;
    flex-direction: column;
    row-gap: 20px;
}

.queue {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    overflow-x: auto;
}

.queue > * {
    margin-right: 10px;
    margin-bottom: 10px;
    width: 50px;
    background-color: #eee;
    text-align: center;
}

@media (prefers-color-scheme: dark) {
    .queue > * {
        background-color: #555;
    }
}

</style>
