// react-exercise/src/components/assignment-components/ElevatorBank.tsx
//import React from 'react'
import { useEffect, useState } from 'react';

import Floor from './Floor.tsx';
import Elevator from './Elevator.tsx';

import '../../styles/Assignments.css';

type ElevatorsType = {
    floors: number[];
}[]

interface ElevatorBankProps {
    elevatorData: { 
        floors: number;
        elevators: {
            floors: {
                start: number;
                end:number
            }[]
        } []
    };
}

const ElevatorBank = ( props: ElevatorBankProps) => {
  
   const [floors, setFloors] = useState<number[]>([]);
   const [elevators, setElevators] = useState<ElevatorsType>([]);
   const [floorRequest, setFloorRequest] = useState ({floorNumber: 1, direction:""});

   useEffect(() => {
    const setupFloors: number[] = Array.from({ length: props.elevatorData.floors });
    setFloors(() => setupFloors);

    const setupElevators = props.elevatorData.elevators.map((e) => {
        let floors: number[] =  [];
        e.floors.forEach((r) => {
            for (let i = r.start; i <= r.end; i++) {
                floors.push(i);
            }
        });
        return { floors };
    });
    setElevators(() => setupElevators);
    }, []); 


  const getFloorPanelButtonConfiguration = ((floorNum:number): string [] => {
    if (floorNum === floors.length - 1){
        return ["", "down"];
    }
    if (floorNum === 0) {
        return ["up", ""];
    }
    return ["up", "down"];
  })

  function  getElevatorPanelButtonConfiguration() {
     return [...floors.keys()].map(f => `${f + 1}`);
  }

 
  function handleUp (data:number) {
    setFloorRequest({floorNumber: data, direction: 'up'});
  };

  
  function handleDown (data:number) {
    setFloorRequest({floorNumber: data, direction: 'down'});
  };

  return (
    <>
    <h1>Assignment Elevator Bank</h1>
    <div className="elevator-bank">
        <div className="floors">
            {floors.map ((floor, index ) => {  
                floorData.floorNumber = index+1;
                floorData.panelButtonConfiguration = getFloorPanelButtonConfiguration(index+1);
                return (
                    <>
                      <Floor floorNumber={index + 1}  panelType='default' floorPanelButtonConfiguration={getFloorPanelButtonConfiguration(index)} onUp={handleUp} onDown={handleDown}  />
                    </>
                )
            })
            }
        </div>
        <div className="elevators">
            {
                elevators.map((elevator, index) => {
                    return (
                        <div className='elevator'>
                        <Elevator  index={index}  floorRequest={floorRequest} elevatorPanelButtonConfiguration={getElevatorPanelButtonConfiguration()} />
                        </div>
                    )  
                })
            }
        </div>
    </div>
    </>
  )
}

//set default props, deprecated to be replaced
const floorData = {
    floorNumber: 0,
    panelButtonConfiguration: ["",""]
}

export default ElevatorBank

// vue-exercise/src/components/assignment-components/elevator-bank.vue
<script>
import Elevator from './elevator.vue'
import Floor from './floor.vue'


export default {
    name: "ElevatorBank",
    components: {
        Elevator,
        Floor,
    },
    props: {
        elevatorData: {}
    },
    data() {
        return {
            setupElevatorData: this.elevatorData,
            floors: [],
            elevators: [],
            floorRequest: {},
        }
    },
    created() {
        this.floors = Array(this.setupElevatorData.floors);
        this.elevators = this.setupElevatorData.elevators.map((e) => {
            // what comes in: {floors: [{start: 1, end: 6}]}
            let floors = [];
            e.floors.forEach((r) => {
                for (let i = r.start; i <= r.end; i++){
                    floors.push(i);
                }
            });
            return {
                floors: floors,
            };
        });
    },
    computed: {
        
    },
    methods: {
        getFloorPanelButtonConfiguration(floorNumber){
            if (floorNumber === this.floors.length - 1){
                return ["", "down"];
            }
            if (floorNumber === 0) {
                return ["up", ""];
            }
            return ["up", "down"];
        },
        getElevatorPanelButtonConfiguration() {
            return [...this.floors.keys()].map(f => f + 1);
        },
        handleUp(data) {
            this.floorRequest = {floorNumber: data, direction: 'up'};
        },
        handleDown(data) {
            this.floorRequest = {floorNumber: data, direction: 'down'};
        },
    },
}


</script>

<template>
    <h1>Assignment Elevator Bank</h1>
    <div class="elevator-bank">
        <div class="floors">
            <Floor v-for="(floor, index) in floors"
                :floor-number="index + 1"
                :floor-panel-button-configuration="getFloorPanelButtonConfiguration(index)"
                @down="handleDown"
                @up="handleUp"

            />
        </div>
        <div class="elevators">
            <Elevator v-for="(elevator, index) in elevators"
                :index="elevator.index"
                :floors="elevator.floors"
                :floor-request="this.floorRequest"
                :elevator-panel-button-configuration="getElevatorPanelButtonConfiguration()"
            />
        </div>
    </div>
</template>

<style scoped>
.floors {
    display: flex;
    flex-direction: column-reverse;
    background-color: #5588ff;
    padding: 3px;
}

.elevator-bank {
    display: flex;
    flex-direction: column;
    row-gap: 20px;
}

.elevator-bank > * {
    background-color: #fff;
}

@media (prefers-color-scheme: dark) {
    .elevator-bank > * {
        background-color: #333;
    }
}
</style>
